stages:
  - preparation
  - test
  - static_analyses
  - code_build
  - container_build

.defaults:
  artifacts:
    untracked: true
  when: manual

get_vendor_dir:
  stage: preparation
  extends: .defaults
  image: golang
  script:
    - go mod vendor
    - go list -m -json -mod=readonly all > go_dependencies.txt

unit_test:
  stage: test
  extends: .defaults
  image: golang
  script:
    - go test --coverprofile=coverage.out $(go list ./... | grep -v mock)  --race ./...
    - go tool cover -func=coverage.out

lint:
  stage: static_analyses
  extends: .defaults
  image: golangci/golangci-lint
  script:
    - golangci-lint run -v --skip-files=".*_mock.go"

dependency_analysis:
  stage: static_analyses
  extends: .defaults
  image: sonatypecommunity/nancy:alpine
  script:
    - cat go_dependencies.txt | nancy sleuth

go_build:
  stage: code_build
  extends: .defaults
  image: golang
  script:
    - if [ "$CI_COMMIT_TAG" != "" ]; then VERSION_TAG="$CI_COMMIT_TAG"; else VERSION_TAG="$CI_COMMIT_SHORT_SHA"; fi
    - go build -ldflags="-X main.ApplicationVersion=$VERSION_TAG" -o bin/app ./cmd/todo

docker_build:
  stage: container_build
  extends: .defaults
  image: gcr.io/kaniko-project/executor:debug
  script:
    - if [ "$CI_COMMIT_TAG" != "" ]; then DOCKER_TAG="$CI_COMMIT_TAG"; else DOCKER_TAG="$CI_COMMIT_SHORT_SHA"; fi
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/build/Dockerfile