version: "3"
services:
  postgres:
    image: postgres
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    expose:
      - 5432
  todo:
    image: todo
    env_file:
      - todo.env
    command: serve --automigrate
    ports:
      - 8080